<?php 
/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */
//import javascripts
function wpbootstrap_scripts_with_jquery()
{
	// Register the script like this for a theme:
	wp_register_script( 'custom-script', get_template_directory_uri() . '/bootstrap/js/bootstrap.js', array( 'jquery' ) );
	// For either a plugin or a theme, you can then enqueue the script:
	wp_enqueue_script( 'custom-script' );
}
add_action( 'wp_enqueue_scripts', 'wpbootstrap_scripts_with_jquery' );

//create nav menu
	if (!function_exists('fleck_theme_setup')) :
	function fleck_theme_setup() {
		//adds the main menu
		register_nav_menus(array(
			'main-menu'=> __('Main Menu','fleck_theme'),
			) );
		}
	endif;
	add_action('after_setup_theme','fleck_theme_setup' );
?>